

    paths:
        /users/{userId}:
            get:
                summary: Get a user by ID
                parameters:
                    - in: path
                      name: userId
                      schema:
                          type: integer
                      required: true
                      description: Numeric ID of the user to get
